import { execFileSync, spawn } from "node:child_process";
import { cpSync, existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { isAbsolute, join, resolve } from "node:path";
import process from "node:process";
import { digestDirectory, digestPluginMcpDispatcherSource, MCP_DISPATCHER_RUNTIME_ENTRIES } from "#agdf-core/runtime/plugin-provenance.js";
import { inspectMcpServerPackage, mcpPackageConstants, prepareMcpServerPackage } from "./package.js";

// Plugin-local AGDF MCP runtime shared by the hosts whose runtime plugin declares the server itself:
// Claude Code passes ${CLAUDE_PLUGIN_DATA}, which it deletes on uninstall; Codex receives an absolute
// AGDF-owned data root from the installer-written declaration. The plugin ships the server and
// dispatcher; only the pinned MCP SDK is installed from npm, once.
const SDK_PACKAGE_SPEC = "@modelcontextprotocol/server@2.0.0";
const STALE_STAGE_MS = 10 * 60 * 1000;
// Without the override the SDK is installed with `npm ci` from the lock the plugin ships and must match
// the shipped digest; the override deliberately restores the unverified install and is recorded.
export const SDK_BUNDLE = Object.freeze({ manifest: "package.json", lock: "package-lock.json", expected: "expected-sdk.json" });
export const SDK_OVERRIDE_ENV = "AGDF_MCP_ALLOW_UNVERIFIED_SDK";
export const SDK_VERIFICATION = Object.freeze({ verified: "verified", override: "unverified_override" });

function readJson(path) {
  try { return JSON.parse(readFileSync(path, "utf8")); } catch { return null; }
}

function ownedRoot(root) {
  return readJson(join(root, mcpPackageConstants.marker))?.owner === mcpPackageConstants.owner;
}

export function pluginMcpVersion(pluginRoot) {
  const version = readJson(join(pluginRoot, "runtime", "runtime-manifest.json"))?.version;
  if (typeof version !== "string" || !version) throw new Error("AGDF_MCP_PLUGIN_RUNTIME_INVALID");
  return version;
}

function copyPluginPackages({ pluginRoot, stage, version }) {
  const serverSource = join(pluginRoot, "mcp", "server");
  const runtimePackage = join(pluginRoot, "runtime", "create-agdf");
  if (!existsSync(join(serverSource, "package.json")) || !existsSync(runtimePackage)) {
    throw new Error("AGDF_MCP_PLUGIN_RUNTIME_INVALID");
  }
  cpSync(serverSource, join(stage, "node_modules", "@agdf", "mcp-server"), { recursive: true });
  const dispatcherRoot = join(stage, "node_modules", "create-agdf");
  for (const entry of MCP_DISPATCHER_RUNTIME_ENTRIES.filter((item) => item !== "package.json")) {
    cpSync(join(runtimePackage, entry), join(dispatcherRoot, entry), { recursive: true });
  }
  writeFileSync(join(dispatcherRoot, "package.json"), `${JSON.stringify({
    name: "create-agdf",
    version,
    private: true,
    type: "module",
    exports: { "./mcp-dispatch-runtime": "./lib/mcp-dispatch-runtime.js" },
    imports: { "#agdf-core": "./runtime/core/lib/index.js", "#agdf-core/*": "./runtime/core/lib/*" },
  }, null, 2)}\n`, "utf8");
}

function pruneMcpDataRoot(mcpDataRoot, version, now) {
  for (const name of readdirSync(mcpDataRoot)) {
    const path = join(mcpDataRoot, name);
    let stats;
    try { stats = lstatSync(path); } catch { continue; }
    if (!stats.isDirectory() || stats.isSymbolicLink() || name === version) continue;
    // Plugin updates keep ${CLAUDE_PLUGIN_DATA}; retire owned runtimes of other versions and
    // stages abandoned by a launcher the host stopped mid-install.
    const staleStage = name.startsWith(".stage-") && now - statSync(path).mtimeMs > STALE_STAGE_MS;
    if (staleStage || (!name.startsWith(".") && ownedRoot(path))) rmSync(path, { recursive: true, force: true });
  }
}

// The locked SDK bundle the plugin ships under mcp/sdk/ (generated by scripts/sync-plugin-mcp.js).
export function readPluginSdkBundle(pluginRoot) {
  const sdkRoot = join(pluginRoot, "mcp", "sdk");
  const expected = readJson(join(sdkRoot, SDK_BUNDLE.expected));
  if (expected?.schema_version !== 1 || typeof expected.sdk_digest !== "string" || !Array.isArray(expected.packages)
      || !existsSync(join(sdkRoot, SDK_BUNDLE.manifest)) || !existsSync(join(sdkRoot, SDK_BUNDLE.lock))) {
    throw new Error("AGDF_MCP_PLUGIN_RUNTIME_INVALID");
  }
  return Object.freeze({ sdkRoot, expected });
}

export function sdkOverrideActive(env = process.env) {
  return env?.[SDK_OVERRIDE_ENV] === "1";
}

export function ensurePluginMcpRuntime({
  pluginRoot,
  dataRoot,
  execPath = process.execPath,
  exec = execFileSync,
  npmOptions = {},
  now = Date.now(),
  env = process.env,
} = {}) {
  if (!pluginRoot || !dataRoot) throw new Error("AGDF_MCP_PLUGIN_DATA_MISSING");
  const version = pluginMcpVersion(pluginRoot);
  const { sdkRoot, expected } = readPluginSdkBundle(pluginRoot);
  const override = sdkOverrideActive(env);
  const mcpDataRoot = join(resolve(dataRoot), "mcp");
  mkdirSync(mcpDataRoot, { recursive: true });
  pruneMcpDataRoot(mcpDataRoot, version, now);
  let current = inspectMcpServerPackage({ dataRoot: mcpDataRoot, expectedVersion: version });
  const sourceServerDigest = digestDirectory(join(pluginRoot, "mcp", "server"));
  const sourceDispatcherDigest = digestPluginMcpDispatcherSource(join(pluginRoot, "runtime", "create-agdf"), version);
  // Without the override only a runtime holding exactly the shipped SDK tree is reused; one installed
  // under the override, or before the plugin shipped an expected digest, is re-verified by replacement.
  const usable = (runtime) => runtime.status === "matched"
    && runtime.digest === sourceServerDigest
    && runtime.dispatcherDigest === sourceDispatcherDigest
    && (override || (runtime.sdkDigest === expected.sdk_digest && runtime.sdkVerification !== SDK_VERIFICATION.override));
  if (usable(current)) return Object.freeze({ ...current, changed: false });
  if (["matched", "mismatch"].includes(current.status) && ownedRoot(current.root)) {
    rmSync(current.root, { recursive: true, force: true });
  } else if (current.status !== "absent") {
    throw new Error("AGDF_MCP_RUNTIME_UNOWNED");
  }
  try {
    const prepared = prepareMcpServerPackage({
      dataRoot: mcpDataRoot,
      expectedVersion: version,
      execPath,
      exec,
      npmOptions,
      expectedSdk: override ? null : expected,
      sdkVerification: override ? SDK_VERIFICATION.override : SDK_VERIFICATION.verified,
      acquire({ stage, install, installLocked }) {
        if (override) {
          install([SDK_PACKAGE_SPEC]);
        } else {
          cpSync(join(sdkRoot, SDK_BUNDLE.manifest), join(stage, "package.json"));
          cpSync(join(sdkRoot, SDK_BUNDLE.lock), join(stage, "package-lock.json"));
          installLocked();
        }
        copyPluginPackages({ pluginRoot, stage, version });
      },
    });
    prepared.commit();
    return prepared;
  } catch (error) {
    // A concurrent session may have installed the same runtime first.
    current = inspectMcpServerPackage({ dataRoot: mcpDataRoot, expectedVersion: version });
    if (usable(current)) return Object.freeze({ ...current, changed: false });
    throw error;
  }
}

// Claude Code passes ${CLAUDE_PLUGIN_DATA} in the environment and needs no arguments. Codex passes no
// plugin variables, so its installer-written declaration names the surface and an absolute data root.
export function parseLauncherArguments(argv, env = {}) {
  const args = [...argv];
  const prepareOnly = args.at(-1) === "--prepare";
  if (prepareOnly) args.pop();
  if (args.length === 0) return { surface: "claude", dataRoot: env.CLAUDE_PLUGIN_DATA, prepareOnly };
  if (args.length === 4 && args[0] === "--surface" && args[1] === "codex" && args[2] === "--data"
      && typeof args[3] === "string" && isAbsolute(args[3])) {
    return { surface: "codex", dataRoot: args[3], prepareOnly };
  }
  return null;
}

// One stderr line per failure: stable code, cause and one recovery action. Plugin skills and hooks do
// not depend on this launcher and keep working while the MCP server is refused.
const LAUNCHER_FAILURES = Object.freeze({
  AGDF_MCP_SDK_PACKAGE_SET_MISMATCH: "the installed MCP SDK packages differ from the lock shipped with this plugin",
  AGDF_MCP_SDK_DIGEST_MISMATCH: "the installed MCP SDK content differs from the version shipped with this plugin",
  AGDF_MCP_PACKAGE_ACQUISITION_FAILED: "npm could not install the locked MCP SDK (network, registry or integrity check)",
  AGDF_MCP_RUNTIME_UNOWNED: "the runtime directory exists but is not owned by AGDF",
  AGDF_MCP_PLUGIN_RUNTIME_INVALID: "the installed AGDF plugin is incomplete",
});

export function launcherFailureLine(code) {
  const cause = LAUNCHER_FAILURES[code] ?? "the AGDF MCP runtime could not be prepared";
  const recovery = ["AGDF_MCP_SDK_PACKAGE_SET_MISMATCH", "AGDF_MCP_SDK_DIGEST_MISMATCH", "AGDF_MCP_PACKAGE_ACQUISITION_FAILED"].includes(code)
    ? `Check your npm registry or mirror and restart; to accept an unverified SDK deliberately, set ${SDK_OVERRIDE_ENV}=1.`
    : code === "AGDF_MCP_RUNTIME_UNOWNED"
      ? "Move the directory away and restart."
      : "Reinstall the AGDF plugin and restart.";
  return `${code}: ${cause}. ${recovery}`;
}

export async function launchPluginMcpServer({
  pluginRoot,
  argv = process.argv.slice(2),
  env = process.env,
  stdout = process.stdout,
  stderr = process.stderr,
  ensure = ensurePluginMcpRuntime,
  execPath = process.execPath,
} = {}) {
  const invocation = parseLauncherArguments(argv, env);
  if (!invocation) {
    stderr.write("AGDF_MCP_ARGUMENTS_INVALID\n");
    process.exitCode = 1;
    return null;
  }
  const { surface, dataRoot, prepareOnly } = invocation;
  let runtime;
  try {
    runtime = ensure({ pluginRoot, dataRoot, env });
  } catch (error) {
    stderr.write(`${launcherFailureLine(/^AGDF_[A-Z_]+/.exec(error?.message ?? "")?.[0] ?? "AGDF_MCP_PLUGIN_RUNTIME_FAILED")}\n`);
    process.exitCode = 1;
    return null;
  }
  // Announced whenever the override is active, also when an existing runtime is reused under it.
  if (sdkOverrideActive(env) || runtime.sdkVerification === SDK_VERIFICATION.override) {
    stderr.write(`AGDF_MCP_SDK_UNVERIFIED_OVERRIDE: ${SDK_OVERRIDE_ENV}=1 is set, so the MCP SDK was not checked against the version shipped with this plugin. Unset it and restart to verify the runtime again.\n`);
  }
  if (prepareOnly) {
    stdout.write(`${JSON.stringify({ status: runtime.status, version: runtime.version, root: runtime.root, changed: runtime.changed })}\n`);
    return runtime;
  }
  // The verified server runs as a child with inherited stdio, exactly as a direct registration
  // would start it; the launcher only forwards termination and the exit status.
  const child = spawn(execPath, [runtime.entrypoint, "--surface", surface], { stdio: "inherit" });
  for (const signal of ["SIGINT", "SIGTERM"]) process.once(signal, () => child.kill(signal));
  return new Promise((resolveExit) => {
    child.once("error", () => { stderr.write("AGDF_MCP_PLUGIN_RUNTIME_FAILED\n"); process.exitCode = 1; resolveExit(null); });
    child.once("exit", (code, signal) => { process.exitCode = code ?? (signal ? 1 : 0); resolveExit(runtime); });
  });
}

export function claudePluginDataRoot({ claudeConfigDir, pluginId = "agdf@agdf" }) {
  // Claude Code names the directory after the plugin id with every character outside [A-Za-z0-9_-]
  // replaced by "-" (agdf@agdf -> agdf-agdf).
  return join(resolve(claudeConfigDir), "plugins", "data", pluginId.replace(/[^A-Za-z0-9_-]/g, "-"));
}

export const claudePluginMcpConstants = Object.freeze({ sdkPackageSpec: SDK_PACKAGE_SPEC, launcher: "mcp/agdf-mcp-launch.js" });

// Codex keeps the plugin-local MCP runtime in an AGDF-owned data root because it passes no plugin data
// directory; `codex plugin remove` cannot delete it. `dataRoot` is the launcher data root (--data);
// uninstall removes it only when it holds nothing but owned runtimes and abandoned stages under mcp/.
export function inspectPluginMcpDataRoot(dataRoot) {
  if (!existsSync(dataRoot)) return "absent";
  try {
    if (!lstatSync(dataRoot).isDirectory() || lstatSync(dataRoot).isSymbolicLink()) return "foreign";
    if (readdirSync(dataRoot).some((name) => name !== "mcp")) return "foreign";
    const mcpDataRoot = join(dataRoot, "mcp");
    if (!existsSync(mcpDataRoot)) return "owned";
    if (!lstatSync(mcpDataRoot).isDirectory() || lstatSync(mcpDataRoot).isSymbolicLink()) return "foreign";
    for (const name of readdirSync(mcpDataRoot)) {
      const path = join(mcpDataRoot, name);
      const stats = lstatSync(path);
      if (!stats.isDirectory() || stats.isSymbolicLink()) return "foreign";
      if (!name.startsWith(".stage-") && !ownedRoot(path)) return "foreign";
    }
    return "owned";
  } catch {
    return "foreign";
  }
}
