import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

// Pages owns the brand values. Tailwind and the cockpit consume this same source.
const source = JSON.parse(readFileSync(new URL('../src/design/tokens.json', import.meta.url), 'utf8'));
export const designTheme = { colors: source.colors, fontFamily: source.fontFamily, borderRadius: source.borderRadius,
  fontSize: Object.fromEntries(Object.entries(source.typography.size).map(([role, size]) =>
    [role, [size, { lineHeight: source.typography.sizeLineHeight[role] }]])), lineHeight: source.typography.lineHeight,
  fontWeight: source.typography.weight, letterSpacing: source.typography.tracking, spacing: source.spacing };
const declarations = [];
for (const [family, shades] of Object.entries(source.colors)) {
  for (const [shade, value] of Object.entries(shades)) declarations.push(`  --agdf-color-${family}-${shade}: ${value};`);
}
for (const [role, families] of Object.entries(source.fontFamily)) {
  declarations.push(`  --agdf-font-${role}: ${families.map(name => name.includes(' ') ? JSON.stringify(name) : name).join(', ')};`);
}
for (const [role, value] of Object.entries(source.borderRadius)) declarations.push(`  --agdf-radius-${role}: ${value};`);
for (const [group, values] of Object.entries(source.typography)) {
  const prefix = { size: 'text', sizeLineHeight: 'text-leading', lineHeight: 'leading', weight: 'weight', tracking: 'tracking' }[group];
  for (const [role, value] of Object.entries(values)) declarations.push(`  --agdf-${prefix}-${role}: ${value};`);
}
for (const [role, value] of Object.entries(source.spacing)) declarations.push(`  --agdf-space-${role}: ${value};`);
for (const [role, value] of Object.entries(source.focus)) declarations.push(`  --agdf-focus-${role}: ${value};`);
const css = `/* Generated by pages/scripts/design-tokens.mjs from src/design/tokens.json. */\n:root {\n${declarations.join('\n')}\n}\n`;
export function writeDesignTokens(check = false) {
  const target = new URL('../src/styles/design-tokens.css', import.meta.url);
  if (check) {
    if (readFileSync(target, 'utf8') !== css) throw Error('AGDF_DESIGN_TOKENS_STALE');
  } else writeFileSync(target, css);
}
if (process.argv[1] === fileURLToPath(import.meta.url)) writeDesignTokens(process.argv.includes('--check'));
