import { createRoot } from 'react-dom/client';
import { BrowserEntry } from './BrowserEntry';
import { consumeSession } from './api';
import './style.css';
import './theme.css';
import './mcp/style.css';
import './browser.css';
const secret = consumeSession();
const root = document.getElementById('root')!;
createRoot(root).render(<BrowserEntry secret={secret} initialCompact={root.dataset.cockpitView === 'compact'}/>);
