import { afterEach, describe, expect, it, vi } from 'vitest';
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { App } from '../src/App';
import { BrowserEntry } from '../src/BrowserEntry';
import type { ReadTransport } from '../src/api';
import type { Detail, Envelope, Inventory } from '../src/types';
const inventory: Envelope<Inventory> = {schema_version:'1',target:{target_id:'target',display_path:'/work/project'},snapshot_id:'snapshot',observed_as_of:'2026-10-06T08:00:00Z',source_digest:'digest',state:'partial',code:'inventory_partial',retryable:false,data:{file_count:1,byte_count:1,runs:[{run_id:'run-a',valid:true,lifecycle:'active',revision_id:'rev',objective:'Goal',title:'Deliver cockpit',source_path:'run.md',status:'open',current_gate:'CD+Tests',code:null}]}};
const detail: Envelope<Detail> = {...inventory,state:'available',code:null,data:{run_id:'run-a',revision_id:'rev',lifecycle:'active',resources:[],persisted:{current_gate:'CD+Tests',decision:'in_progress',next_allowed_action:'Implement approved scope',artefacts:[]},evaluation:{status:'open',control_assessment:{state:'open',authorizes:false},current_gate:'CD+Tests',blocking_reason:'none',missing_approval:'none',next_allowed_action:'Implement approved scope',next_action_de:'Freigegebenen Umfang umsetzen.',doctor_status:'pass',quality_outlook:'',git_evidence:'unavailable',diagnostics:[],approvals:[{gate:'TP',status:'approved',evidence:'exact approval'},{gate:'QA',status:'missing',evidence:''}],missing_evidence:[{missing_evidence:'Host context still unverified'}]}}};
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.useRealTimers();vi.unstubAllGlobals();});
const changed = {...inventory,state:'stale' as const,code:'source_changed',data:null};
function advanced() {
  const nextInventory = {...inventory,snapshot_id:'snapshot-2',data:{...inventory.data!,runs:inventory.data!.runs.map(run=>({...run,revision_id:'rev-2',current_gate:'QA'}))}};
  const nextDetail = {...detail,snapshot_id:'snapshot-2',data:{...detail.data!,revision_id:'rev-2',persisted:{...detail.data!.persisted!,current_gate:'QA',next_allowed_action:'Check quality'},evaluation:{...detail.data!.evaluation!,current_gate:'QA',next_allowed_action:'Check quality',next_action_de:'Qualität prüfen.'}}};
  return {nextInventory,nextDetail};
}
async function readySelection() {
  const select = await screen.findByRole('combobox', { name: 'Run auswählen' });
  await waitFor(() => expect((select as HTMLSelectElement).disabled).toBe(false));
  return select;
}
async function tick() { await act(async()=>{await vi.advanceTimersByTimeAsync(5000);}); }
describe('compact MCP entry using the shared reading state',()=>{
  it('searches a large inventory without selecting a result or losing the inspected run',async()=>{
    const many={...inventory,data:{...inventory.data!,runs:[...inventory.data!.runs,...Array.from({length:12},(_,i)=>({...inventory.data!.runs[0],run_id:`other-${i}`,title:`Other project ${i}`}))]}};
    const transport=vi.fn(async(path:string)=>path.startsWith('/api/runs/')?detail:many) as unknown as ReadTransport;
    render(<App compact transport={transport}/>);
    const select=await readySelection();
    fireEvent.change(screen.getByRole('searchbox',{name:'Runs suchen'}),{target:{value:'other-7'}});
    expect(screen.getAllByRole('option')).toHaveLength(2);
    expect((select as HTMLSelectElement).value).toBe('');expect(transport).toHaveBeenCalledTimes(1);
    fireEvent.change(screen.getByRole('searchbox'),{target:{value:''}});
    fireEvent.change(select,{target:{value:'run-a'}});await screen.findByText('Freigegebenen Umfang umsetzen.');
    fireEvent.change(screen.getByRole('searchbox'),{target:{value:'no match'}});
    expect((select as HTMLSelectElement).value).toBe('run-a');
    expect(screen.getByRole('heading',{name:'Deliver cockpit'})).toBeTruthy();
    expect(screen.getByText('0 Treffer · Die aktuelle Auswahl bleibt erhalten.')).toBeTruthy();
    expect(transport).toHaveBeenCalledTimes(2);
  });
  it('identifies partial inventory entries and opens their available diagnostics explicitly',async()=>{
    const bad={...inventory.data!.runs[0],run_id:'invalid-run',title:'Broken run',valid:false,code:'invalid_run',source_path:'.agdf/control/runs/invalid-run/RUN_STATE.md'};
    const partial={...inventory,data:{...inventory.data!,runs:[...inventory.data!.runs,bad]}};
    const invalid={...detail,state:'invalid' as const,code:'invalid_run',data:{run_id:'invalid-run',revision_id:null,lifecycle:null,resources:[]}};
    const transport=vi.fn(async(path:string)=>path.startsWith('/api/runs/invalid-run')?invalid:partial) as unknown as ReadTransport;
    render(<App compact transport={transport}/>);
    await readySelection();
    const hints=screen.getByText('1 von 2 Runs eingeschränkt',{exact:false}).closest('details');
    expect(hints?.hasAttribute('open')).toBe(false);
    expect(screen.getByText(bad.source_path)).toBeTruthy();
    fireEvent.click(screen.getByRole('button',{name:'Broken run · invalid-run'}));
    await screen.findByRole('heading',{name:'Broken run'});
    expect(screen.getByText('Dieser Run ist ungültig. Die Quelldaten außerhalb des Cockpits prüfen.')).toBeTruthy();
    expect(vi.mocked(transport).mock.calls[1][0]).toBe('/api/runs/invalid-run?snapshot=snapshot');
  });
  it('summary and details remain in the expanded browser reader without resetting or re-reading the Run',async()=>{
    const transport=vi.fn(async(path:string)=>path.startsWith('/api/runs/')?detail:inventory) as unknown as ReadTransport;
    render(<BrowserEntry initialCompact transport={transport}/>);
    expect((await readySelection() as HTMLSelectElement).value).toBe('');
    expect(screen.queryByRole('button',{name:'Run ansehen'})).toBeNull();
    fireEvent.change(screen.getByRole('combobox'),{target:{value:'run-a'}});
    await screen.findByText('Freigegebenen Umfang umsetzen.');
    fireEvent.click(screen.getByRole('button',{name:'Run ansehen'}));
    const heading=await screen.findByRole('heading',{name:'Deliver cockpit'});
    expect(document.activeElement).toBe(heading);expect(screen.getByText('run-a',{exact:true})).toBeTruthy();
    const summary=screen.getByRole('button',{name:'Zusammenfassung'});
    expect(summary.closest('[aria-label="Ansicht"]')).toBeTruthy();
    expect(screen.getByRole('button',{name:'Zusammenfassung'}).getAttribute('aria-pressed')).toBe('true');
    expect(screen.getByRole('button',{name:'Alle Vorhaben'}).closest('nav')?.getAttribute('aria-label')).toBe('Vorhaben-Pfad');
    expect(screen.getByRole('button',{name:'Neu laden'}).closest('.cockpit-brand-header')).toBeTruthy();
    fireEvent.click(summary);
    expect(screen.getByRole('button',{name:'Zusammenfassung'}).getAttribute('aria-pressed')).toBe('true');
    expect(screen.queryByRole('button',{name:'Run ansehen'})).toBeNull();
    expect(screen.queryByRole('heading',{name:'Dokumente'})).toBeNull();
    expect(screen.getByRole('heading',{name:'Deliver cockpit',level:1})).toBeTruthy();
    fireEvent.click(screen.getByRole('button',{name:'Details'}));
    expect(screen.getByRole('heading',{name:'Dokumente'})).toBeTruthy();
    expect(screen.getByRole('button',{name:'Details'}).getAttribute('aria-pressed')).toBe('true');
    expect(transport).toHaveBeenCalledTimes(2);
    expect(vi.mocked(transport).mock.calls.map(call=>call[0])).toEqual(['/api/snapshot','/api/runs/run-a?snapshot=snapshot']);
  });
  it('the default browser entry retains the full reader and does not select a run',async()=>{
    const transport=vi.fn(async()=>inventory) as unknown as ReadTransport;
    render(<BrowserEntry transport={transport}/>);
    await screen.findByRole('button',{name:'Deliver cockpit'});
    expect(screen.getByRole('heading',{name:'Run-Übersicht'})).toBeTruthy();
    expect(screen.queryByRole('group',{name:'Ansicht'})).toBeNull();
    expect(screen.queryByRole('button',{name:'Dokument schließen'})).toBeNull();
    expect(transport).toHaveBeenCalledTimes(1);
  });
  it('documents have no Run content switch; the parent breadcrumb restores Run details and source focus',async()=>{
    const resource={resource_id:'source-a',run_id:'run-a',type:'UR',path:'UR.md',registered_reference:'UR.md',status:'approved'};
    const withSource={...detail,data:{...detail.data!,resources:[resource]}};
    const documentResult={...inventory,state:'available',code:null,data:{resource,format:'markdown',content:'# Original document\nExact source content',content_digest:'source-digest'}};
    const transport=vi.fn(async(path:string)=>path.startsWith('/api/documents/')?documentResult:path.startsWith('/api/runs/')?withSource:inventory) as unknown as ReadTransport;
    render(<App initialRunId="run-a" transport={transport}/>);
    await screen.findByRole('heading',{name:'Deliver cockpit',level:1});
    expect(screen.getByRole('button',{name:'Zusammenfassung'}).getAttribute('aria-pressed')).toBe('true');
    fireEvent.click(screen.getByRole('button',{name:'Details'}));
    fireEvent.click(screen.getByRole('button',{name:/^Anforderungen Beschreibt/}));
    await screen.findByText('Originaldokument lesen',{exact:true});
    fireEvent.click(screen.getByText('Originaldokument lesen',{exact:true}));
    await screen.findByRole('heading',{name:'Original document'});
    expect(vi.mocked(transport).mock.calls.map(call=>call[0])).toEqual(['/api/snapshot','/api/runs/run-a?snapshot=snapshot','/api/runs/run-a?snapshot=snapshot','/api/documents/source-a?snapshot=snapshot']);
    expect(screen.queryByRole('group',{name:'Ansicht'})).toBeNull();
    expect(screen.queryByRole('button',{name:'Zusammenfassung'})).toBeNull();
    expect(screen.queryByRole('button',{name:'Details'})).toBeNull();
    expect(screen.getByRole('heading',{name:'Anforderungen',level:1})).toBeTruthy();
    expect(transport).toHaveBeenCalledTimes(4);
    fireEvent.click(screen.getByRole('button',{name:'Deliver cockpit'}));
    await screen.findByRole('heading',{name:'Deliver cockpit',level:1});
    expect(screen.getByRole('button',{name:'Details'}).getAttribute('aria-pressed')).toBe('true');
    expect(screen.getByRole('button',{name:/^Anforderungen Beschreibt/})).toBe(document.activeElement);
    expect(transport).toHaveBeenCalledTimes(5);
    expect(screen.queryByRole('button',{name:'Dokument schließen'})).toBeNull();
    fireEvent.click(screen.getByRole('button',{name:/^Anforderungen Beschreibt/}));
    await screen.findByText('Originaldokument lesen',{exact:true});
    fireEvent.click(screen.getByText('Originaldokument lesen',{exact:true}));
    await screen.findByRole('heading',{name:'Original document'});
    const close=screen.getByRole('button',{name:'Dokument schließen'});
    expect(close.getAttribute('title')).toBe('Dokument schließen');
    fireEvent.click(close);
    await screen.findByRole('heading',{name:'Deliver cockpit',level:1});
    expect(screen.getByRole('button',{name:'Details'}).getAttribute('aria-pressed')).toBe('true');
    expect(screen.getByRole('button',{name:/^Anforderungen Beschreibt/})).toBe(document.activeElement);
    expect(vi.mocked(transport).mock.calls.at(-1)?.[0]).toBe('/api/runs/run-a?snapshot=snapshot');
    expect(transport).toHaveBeenCalledTimes(8);
  });
  it('reads before expansion, requires explicit run selection and preserves it when expanded',async()=>{
    const transport = vi.fn(async(path:string)=>path.startsWith('/api/runs/')?detail:inventory) as unknown as ReadTransport;
    const expand=vi.fn();
    const view=render(<App compact transport={transport} onExpand={expand}/>);
    const select=await readySelection();
    expect((select as HTMLSelectElement).value).toBe('');
    expect(transport).toHaveBeenCalledTimes(1);
    expect(screen.queryByText('Freigegebenen Umfang umsetzen.')).toBeNull();
    fireEvent.change(select,{target:{value:'run-a'}});
    await screen.findByText('Freigegebenen Umfang umsetzen.');
    expect(screen.getByRole('heading',{name:'Deliver cockpit'})).toBeTruthy();
    const inventoryHints = screen.getByText('Inventarhinweise').closest('details');
    expect(inventoryHints?.hasAttribute('open')).toBe(false);
    expect(screen.getByText('Host context still unverified')).toBeTruthy();
    expect(screen.getByText('Zuletzt als „In Arbeit“ gespeichert.')).toBeTruthy();
    expect(screen.getByText('Umsetzungs- und Prüfplan · freigegeben',{exact:true})).toBeTruthy();
    expect(screen.queryByText('QA',{exact:true})).toBeNull();
    fireEvent.click(screen.getByRole('button',{name:'Run ansehen'}));expect(expand).toHaveBeenCalledTimes(1);
    view.rerender(<App transport={transport} onExpand={expand}/>);
    expect(screen.getByRole('heading',{name:'Deliver cockpit'})).toBeTruthy();
    expect(screen.getByText('run-a',{exact:true})).toBeTruthy();
    expect(transport).toHaveBeenCalledTimes(2);
  });
  it('failed reload retains stale sources and prevents expansion as a fresh run',async()=>{
    let fail=false;
    const transport=vi.fn(async(path:string)=>{if(fail)throw Error('read_failed');return path.startsWith('/api/runs/')?detail:inventory;}) as unknown as ReadTransport;
    render(<App compact transport={transport} onExpand={vi.fn()}/>);
    fireEvent.change(await readySelection(),{target:{value:'run-a'}});
    await screen.findByText('Freigegebenen Umfang umsetzen.');fail=true;
    fireEvent.click(screen.getByRole('button',{name:'Neu laden'}));
    await screen.findByText('Die Daten konnten nicht gelesen werden. Quelle oder lokalen Dienst prüfen und wiederholen.');
    expect((screen.getByRole('button',{name:'Run ansehen'}) as HTMLButtonElement).disabled).toBe(true);
    expect(screen.getByText('Host context still unverified')).toBeTruthy();
    expect(screen.queryByRole('button',{name:/Approval/})).toBeNull();
  });
  it('refreshes a changed gate coherently without changing selection or keyboard focus',async()=>{
    vi.useFakeTimers({toFake:['setInterval','clearInterval']});
    const {nextInventory,nextDetail}=advanced();let updated=false;
    const transport=vi.fn(async(path:string)=>path.startsWith('/api/freshness')?changed:path.startsWith('/api/runs/')?(updated?nextDetail:detail):(updated?nextInventory:inventory)) as unknown as ReadTransport;
    render(<App compact transport={transport} onExpand={vi.fn()}/>);
    const select=await readySelection();fireEvent.change(select,{target:{value:'run-a'}});
    await screen.findByText('Freigegebenen Umfang umsetzen.');select.focus();updated=true;
    await tick();await screen.findByText('Qualität prüfen.');
    expect((select as HTMLSelectElement).value).toBe('run-a');expect(document.activeElement).toBe(select);
    expect(screen.getByRole('heading',{name:'Qualitätsprüfung'})).toBeTruthy();
    expect(screen.queryByText('Kontrolldaten werden gelesen … Vorheriger Datenstand bleibt sichtbar.')).toBeNull();
    expect(vi.mocked(transport).mock.calls.map(call=>call[0])).toEqual(['/api/snapshot','/api/runs/run-a?snapshot=snapshot','/api/freshness?snapshot=snapshot','/api/snapshot','/api/runs/run-a?snapshot=snapshot-2']);
  });
  it('pauses while outside the viewport or document is hidden and checks upon return',async()=>{
    vi.useFakeTimers({toFake:['setInterval','clearInterval']});
    let visibility!: IntersectionObserverCallback;
    const disconnect=vi.fn();
    vi.stubGlobal('IntersectionObserver',class {constructor(callback:IntersectionObserverCallback){visibility=callback;}observe(){}disconnect=disconnect;});
    const transport=vi.fn(async(path:string)=>path.startsWith('/api/freshness')?{...inventory,state:'available',code:null,data:{unchanged:true}}:inventory) as unknown as ReadTransport;
    render(<App compact transport={transport}/>);await readySelection();
    await tick();expect(transport).toHaveBeenCalledTimes(1);
    await act(async()=>visibility([{isIntersecting:true,intersectionRatio:1} as IntersectionObserverEntry],{} as IntersectionObserver));
    expect(transport).toHaveBeenCalledTimes(2);
    await act(async()=>visibility([{isIntersecting:false,intersectionRatio:0} as IntersectionObserverEntry],{} as IntersectionObserver));
    await tick();expect(transport).toHaveBeenCalledTimes(2);
    vi.spyOn(document,'hidden','get').mockReturnValue(true);
    await act(async()=>visibility([{isIntersecting:true,intersectionRatio:1} as IntersectionObserverEntry],{} as IntersectionObserver));
    await tick();expect(transport).toHaveBeenCalledTimes(2);
    vi.spyOn(document,'hidden','get').mockReturnValue(false);
    await act(async()=>document.dispatchEvent(new Event('visibilitychange')));
    expect(transport).toHaveBeenCalledTimes(3);
    cleanup();expect(disconnect).toHaveBeenCalledTimes(1);
  });
  it('retains stale evidence on automatic read failure and recovers only on explicit retry',async()=>{
    vi.useFakeTimers({toFake:['setInterval','clearInterval']});let fail=false;
    const transport=vi.fn(async(path:string)=>{if(path.startsWith('/api/freshness'))return changed;if(fail)throw Error('read_failed');return path.startsWith('/api/runs/')?detail:inventory;}) as unknown as ReadTransport;
    render(<App compact transport={transport} onExpand={vi.fn()}/>);
    fireEvent.change(await readySelection(),{target:{value:'run-a'}});
    await screen.findByText('Freigegebenen Umfang umsetzen.');fail=true;await tick();
    await screen.findByText('Die Daten konnten nicht gelesen werden. Quelle oder lokalen Dienst prüfen und wiederholen.');
    expect((screen.getByRole('button',{name:'Run ansehen'}) as HTMLButtonElement).disabled).toBe(true);
    const count=vi.mocked(transport).mock.calls.length;await tick();expect(transport).toHaveBeenCalledTimes(count);
    fail=false;fireEvent.click(screen.getByRole('button',{name:'Neu laden'}));
    await screen.findByRole('button',{name:'Run ansehen'});
    await act(async()=>{});
    expect(screen.queryByText('Vorheriger Datenstand · Bitte neu laden.')).toBeNull();
  });
  it('discards an obsolete freshness response after explicit selection of another run',async()=>{
    vi.useFakeTimers({toFake:['setInterval','clearInterval']});let resolve!: (value:typeof changed)=>void;
    const two={...inventory,data:{...inventory.data!,runs:[...inventory.data!.runs,{...inventory.data!.runs[0],run_id:'run-b',title:'Second run'}]}};
    const transport=vi.fn(async(path:string)=>path.startsWith('/api/freshness')?new Promise<typeof changed>(done=>{resolve=done;}):path.startsWith('/api/runs/run-b')?{...detail,data:{...detail.data!,run_id:'run-b'}}:path.startsWith('/api/runs/')?detail:two) as unknown as ReadTransport;
    render(<App compact transport={transport}/>);
    const select=await readySelection();fireEvent.change(select,{target:{value:'run-a'}});
    await screen.findByText('Freigegebenen Umfang umsetzen.');await tick();
    fireEvent.change(select,{target:{value:'run-b'}});await screen.findByRole('heading',{name:'Second run'});
    await act(async()=>resolve(changed));
    expect((select as HTMLSelectElement).value).toBe('run-b');
    expect(vi.mocked(transport).mock.calls.filter(call=>call[0]==='/api/snapshot')).toHaveLength(1);
  });
  it('returns to overview if the selected run disappears instead of selecting a replacement',async()=>{
    vi.useFakeTimers({toFake:['setInterval','clearInterval']});let removed=false;
    const transport=vi.fn(async(path:string)=>path.startsWith('/api/freshness')?changed:path.startsWith('/api/runs/')?detail:removed?{...inventory,snapshot_id:'snapshot-2',data:{...inventory.data!,runs:[{...inventory.data!.runs[0],run_id:'run-b'}]}}:inventory) as unknown as ReadTransport;
    render(<App compact transport={transport}/>);const select=await readySelection();
    fireEvent.change(select,{target:{value:'run-a'}});await screen.findByText('Freigegebenen Umfang umsetzen.');removed=true;
    await tick();expect((select as HTMLSelectElement).value).toBe('');
    expect(screen.queryByText('Freigegebenen Umfang umsetzen.')).toBeNull();
    expect(vi.mocked(transport).mock.calls.some(call=>call[0].startsWith('/api/runs/run-b'))).toBe(false);
  });
  it('allows explicit selection to supersede a pending background read without mixing source views',async()=>{
    vi.useFakeTimers({toFake:['setInterval','clearInterval']});
    const {nextInventory,nextDetail}=advanced();let updated=false,finish!: (value:typeof nextDetail)=>void;
    const two={...nextInventory,data:{...nextInventory.data!,runs:[...nextInventory.data!.runs,{...nextInventory.data!.runs[0],run_id:'run-b',title:'Second run'}]}};
    const transport=vi.fn(async(path:string)=>{
      if(path.startsWith('/api/freshness'))return changed;
      if(path.startsWith('/api/runs/run-b'))return {...nextDetail,data:{...nextDetail.data!,run_id:'run-b'}};
      if(path==='/api/runs/run-a?snapshot=snapshot-2')return new Promise<typeof nextDetail>(resolve=>{finish=resolve;});
      if(path.startsWith('/api/runs/'))return detail;
      return updated?two:inventory;
    }) as unknown as ReadTransport;
    render(<App compact transport={transport}/>);const select=await readySelection();
    fireEvent.change(select,{target:{value:'run-a'}});await screen.findByText('Freigegebenen Umfang umsetzen.');
    updated=true;await tick();await screen.findByText('Kontrolldaten werden gelesen … Vorheriger Datenstand bleibt sichtbar.');
    // The currently displayed selector still contains the previous inventory; selecting its overview
    // re-reads first, making the newly discovered run available without accepting the pending A reply.
    fireEvent.change(select,{target:{value:''}});await screen.findByText('Wähle einen Run für Status, offene Nachweise und den nächsten erlaubten Schritt.');
    fireEvent.change(select,{target:{value:'run-b'}});await screen.findByRole('heading',{name:'Second run'});
    await act(async()=>finish(nextDetail));
    expect((select as HTMLSelectElement).value).toBe('run-b');
    expect(screen.queryByText('Kontrolldaten werden gelesen … Vorheriger Datenstand bleibt sichtbar.')).toBeNull();
    expect(screen.getByText('Qualität prüfen.')).toBeTruthy();
  });
});

it('keeps a stale Run identified and qualifies the previous step with one read warning until explicit reload',async()=>{
  const goodDetail={...detail,state:'available' as const,code:null};
  const read=vi.fn(async(path:string)=>path.startsWith('/api/freshness')?changed:path.startsWith('/api/runs/')?goodDetail:inventory) as unknown as ReadTransport;
  render(<App initialRunId="run-a" transport={read}/>);
  await screen.findByText('Weiterarbeit offen');
  fireEvent.click(screen.getByRole('button',{name:'Zusammenfassung'}));
  expect(screen.getByText('Ziel und Run-ID · Originalangaben').closest('details')?.open).toBe(false);
  expect(screen.getByText('Nachweise und offene Punkte · 1').closest('details')?.open).toBe(false);
  expect(screen.getByText('Weiterarbeit offen')).toBeTruthy();
  await act(async()=>document.dispatchEvent(new Event('visibilitychange')));
  await screen.findByText('Aktuelle Voraussetzungen nicht bestätigt');
  expect(screen.queryByText('Weiterarbeit offen')).toBeNull();
  expect(screen.queryByText(/Angefragter Run:/)).toBeNull();
  expect(screen.queryByText('Voraussetzungen · aktueller Kontrollstand')).toBeNull();
  expect(screen.getAllByText('Die Quelldaten haben sich geändert. Angezeigte Inhalte gehören zum vorherigen Datenstand. Bewusst neu laden.')).toHaveLength(1);
  expect(document.querySelector('footer')?.textContent).toContain('Veraltet');
  fireEvent.click(screen.getByRole('button',{name:'Daten aktualisieren'}));
  await screen.findByText('Weiterarbeit offen');
  expect(document.querySelector('footer')?.textContent).toContain('Verfügbar');
  expect(screen.getByRole('heading',{name:'Deliver cockpit'})).toBeTruthy();
});

it('exposes an inventory failure directly instead of hiding it in ordinary inventory hints',async()=>{
 const read=vi.fn(async()=>({...inventory,state:'error',code:'timeout',data:null,retryable:true})) as unknown as ReadTransport;
 render(<App compact transport={read} onExpand={vi.fn()}/>);
 await screen.findByText('Das Lesen hat das Zeitlimit erreicht. Quelle und Umfang prüfen, dann wiederholen.');
 expect(screen.queryByText('Inventarhinweise')).toBeNull();
 expect((screen.getByRole('button',{name:'Run-Übersicht'}) as HTMLButtonElement).disabled).toBe(true);
});

it('opens the exact registered Run State from an unconfirmed card even when the host leaves it inline',async()=>{
 const source={resource_id:'opaque-state',run_id:'run-a',type:'Run State',path:null,registered_reference:'.agdf/control/runs/run-a/RUN_STATE.md',status:'registered'};
 const observed={...detail,data:{...detail.data!,resources:[source],evaluation:{...detail.data!.evaluation!,control_assessment:undefined}}};
 const read=vi.fn(async(path:string)=>path.startsWith('/api/documents/')?{...detail,data:{resource:source,format:'markdown',content:'# Exact Run State\n\nSaved source content.',links:{}}}:path.startsWith('/api/runs/')?observed:inventory) as unknown as ReadTransport;
 const expand=vi.fn();render(<App compact initialRunId="run-a" transport={read} onExpand={expand}/>);
 await screen.findByText('Aktuelle Voraussetzungen nicht bestätigt');
 fireEvent.click(screen.getByRole('button',{name:'Stand des Vorhabens öffnen'}));
 await screen.findByText('Originaldokument lesen',{exact:true});
    fireEvent.click(screen.getByText('Originaldokument lesen',{exact:true}));
    await screen.findByRole('heading',{name:'Exact Run State'});
 expect(expand).toHaveBeenCalledTimes(1);
 expect(vi.mocked(read).mock.calls.at(-1)?.[0]).toBe('/api/documents/opaque-state?snapshot=snapshot');
 expect(vi.mocked(read).mock.calls.at(-1)?.[2]).toEqual({target:'target',snapshot:'snapshot'});
 fireEvent.click(screen.getByRole('button',{name:'Zurück zum Arbeitsstand'}));
 await screen.findByText('Aktuelle Voraussetzungen nicht bestätigt');
 expect(screen.queryByRole('combobox')).toBeNull();expect(screen.getByRole('heading',{name:'Deliver cockpit'})).toBeTruthy();
});
